name: Update gist with WakaTime stats
on:
  schedule:
    - cron: '*/10 * * * *'
jobs:
  update-gist:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Install Dependencies
        run: npm install
      - name: Update gist
        run: node index.js
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          GIST_ID: 71ddbf5ee0432da77214b56cbe8840cf
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
